{% set name = "talipp" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/talipp-{{ version }}.tar.gz
  sha256: 61d9a0deb7208f52843f29fbe19f9b1ecabf8b66afd9f8144f89a7fc5cb16ce3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - talipp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nardew/talipp
  summary: TALi++ - Incremental Technical Analysis Library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nardew
