{% set name = "talipp" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/talipp-{{ version }}.tar.gz
  sha256: 41326000305c9ead01031b7973386aea57ab30c025b6142615f7bb78f06d8967

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - talipp
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nardew/talipp
  summary: TALi++ - Incremental Technical Analysis Library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nardew
